[theme]
base = "dark"
primaryColor = "#0099ff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
font = "monospace"

[server]
headless = true

[browser]
gatherUsageStats = false
